src/umvc_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("web/", include("webapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/webapp/urls.py
# Inside your Django app (e.g., webapp/urls.py)
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = "web"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("login/", LoginView.as_view(template_name="webapp/login.html"), name="login"),
    path("signup/", views.signup, name="signup"),
    # path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # path('vision/', views.vision, name='vision'),
    # path('history/', views.history, name='history'),
    # path('activities/', views.activities, name='activities'),
    # path('member-gallery/', views.member_gallery, name='member_gallery'),
    path("reports/", views.ReportsView.as_view(), name="reports"),
    path("reports/<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("reports/<int:report_id>/update", views.update_report, name="update_report"),
    path("reports/upload/", views.upload_report, name="upload_report"),
]

src/webapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
import datetime


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Report(models.Model):
    name = models.CharField(max_length=255)
    pub_date = models.DateTimeField(default=timezone.now)
    # tags = models.CharField(max_length=255)
    tags = models.ManyToManyField(
        Tag, related_name="reports"
    )  # access the set of reports from a Tag (e.g., some_tag.reports.all()).
    description = models.TextField()
    file = models.FileField(upload_to="reports", blank=True, null=True)
    
    class Meta:
        permissions = [
            ("can_view_reports", "Can view reports"),
        ]

    def __str__(self):
        return self.name

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        """
        Only return True if the date is in the past
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

src/webapp/forms.py
# forms.py in your app directory
# from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Report


class ReportForm(ModelForm):
    class Meta:
        model = Report
        fields = ["name", "pub_date", "description", "file"]


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

src/webapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
    PermissionRequiredMixin,
)
from django.core.exceptions import PermissionDenied
from .forms import ReportForm, SignUpForm
from django.contrib.auth import login
from .models import Report

# def member_gallery(request):
#     return render(request, 'member_gallery.html')


# def reports(request):
#     # This view will later include logic to check if a user is logged in and has member access
#     latest_report_list = Report.objects.order_by("-pub_date")[:5]
#     context = {
#         "latest_report_list": latest_report_list,
#     }
#     return render(request, "webapp/reports.html", context)
#     # return HttpResponse(template.render(context, request))
#     # output = ", ".join([r.name for r in latest_report_list])
#     # return HttpResponse(output)


# def detail(request, report_id):
#     try:
#         report = Report.objects.get(pk=report_id)
#     except Report.DoesNotExist:
#         raise Http404("Report does not exist")
#     return render(request, "webapp/detail.html", {"report": report})
# ======= A Better Coding =============
# def detail(request, report_id):
#     report = get_object_or_404(Report, pk=report_id)
#     return render(request, "webapp/detail.html", {"report": report})
# ======= A BETTER Better Coding (Generic View)=============


class HomeView(generic.TemplateView):
    template_name = "webapp/home.html"


class DetailView(generic.DetailView):
    model = Report
    template_name = "webapp/detail.html"


class ReportsView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    login_url = "web:login"
    redirect_field_name = "web:reports"

    model = Report
    template_name = "webapp/reports.html"
    context_object_name = "latest_report_list"
    permission_required = ["webapp.view_report"]

    # def test_func(self):
    #     """
    #     This method is required by UserPassesTestMixin to determine if the user passes a certain condition.
    #     """
    #     return self.request.user.has_perm("webapp.can_view_reports")

    def handle_no_permission(self):
        """
        Override the method to provide custom behavior when the user fails the test.
        """
        if not self.request.user.is_authenticated:
            # Redirects to login page if the user isn't authenticated
            return super().handle_no_permission()
        else:
            # Raises a permission denied error if the user doesn't have the permission
            raise PermissionDenied(
                "Sorry, you do not have permission to view reports. Please contact admin."
            )

    def get_queryset(self):
        """
        Return the last five published reports (not including those set to be
        published in the future).
        """
        return Report.objects.filter(pub_date__lte=timezone.now()).order_by(
            "-pub_date"
        )[:5]


def upload_report(request):
    if request.method == "POST":
        form = ReportForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("web:reports")
    else:
        form = ReportForm()
    return render(request, "webapp/upload_report.html", {"form": form})


def update_report(request, report_id):
    """Update an existing report"""
    return render(request, "webapp/home.html")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Log the user in
            return redirect(
                "web:home"
            )  # Redirect to a home page or another appropriate page
    else:
        form = SignUpForm()
    return render(request, "webapp/signup.html", {"form": form})

src/webapp/templates/webapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'webapp/style.css' %}">
    <title>University Melbourne Venture Club</title>
</head>
<body>
    {% block content %}
    <!-- Default content goes here. This will be overridden by child templates. -->
    {% endblock %}
</body>
</html>

src/webapp/templates/webapp/detail.html
{% extends "webapp/base.html" %}

{% block content %}
<form action="{% url 'web:update_report' report.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ report.name }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for tag in report.tags.all %}
            <input type="radio" name="tag" id="tag{{ forloop.counter }}" value="{{ tag.id }}">
            <label for="tag{{ forloop.counter }}">{{ tag.name }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Update report">
</form>


<h2>{{ report.name }}</h2>
{% if report.file %}
    <h3> {{ report.file.url }} </h3>    
    <iframe src="{{ report.file.url }}" width="100%" height="500" style="border: none;" allowfullscreen></iframe>
{% else %}
    <p>No file is available.</p>
{% endif %}
{% endblock %}

src/webapp/templates/webapp/home.html
{% extends "webapp/base.html" %}

{% block content %}
<h1>Welcome to the University Melbourne Venture Club</h1>
<a href="{% url 'web:signup' %}">Sign Up</a>
{% endblock %}

src/webapp/templates/webapp/login.html
{% extends "webapp/base.html" %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  {% comment %} <p>Don't have an account? <a href="{% url 'web:signup' %}">Sign up now</a></p> {% endcomment %}
{% endblock %}

src/webapp/templates/webapp/reports.html
{% extends "webapp/base.html" %}

{% block content %}
{% if latest_report_list %}
    <ul>
    {% for report in latest_report_list %}
        <li><a href="{% url 'web:detail' report.id %}">{{ report.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No reports are available.</p>
{% endif %}
{% endblock %}

src/webapp/templates/webapp/signup.html
{% extends "webapp/base.html" %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock %}

src/webapp/templates/webapp/upload_report.html
{% extends "webapp/base.html" %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
{% endblock %}